### ISSUE TITLE
ทำไม Course Code สำหรับ Join Course มันไม่คงตัว

### ISSUE THREAD

**Issue by pinyotae** [Thanadej8/Coderoom#17]
ไม่รู้ว่าเป็นการออกแบบให้โค้ดเปลี่ยนไปเรื่อย ๆ เพื่อป้องกันโค้ดรั่วแล้วโดนใช้งานต่อเนื่องนานเกินหรือว่าเป็นบั๊ก ซึ่งผมสังเกตมาแล้ว 4 วาระที่ได้โค้ดไม่เหมือนเดิม สองครั้งล่าสุดผมจึงบันทึกไว้ได้โค้ดดังนี้ 
T8dLQZ และ TBc6qR

โค้ดมาจากเครื่อง IP http://172.27.225.82 ทั้งสองตัว ไม่ทราบว่ามันเกิดอะไรขึ้น พอจะอธิบายได้ไหม

**Comment by Thanadej8** [comment]
พีมิก รีดาต้าเบสใหม่มันเลยเจน token ใหม่ครับ

**Comment by Thanadej8** [comment]
@MigMikael
