### ISSUE TITLE
ไม่มีหน้าแสดง IP ของผู้เข้าสอบหรือเปล่า

### ISSUE THREAD

**Issue by pinyotae** [Thanadej8/Coderoom#5]
ไม่มีหน้าแสดง IP ของผู้เข้าสอบหรือเปล่า คือในระหว่างการสอบจะมองเห็นได้ยังไงว่าใครล็อกอินเข้ามาแล้ว และล็อกมาเวลาไหน

**Comment by Thanadej8** [comment]
อันนี้มีอยู่แล้วนะครับอยู่ในหน้า ที่โชวเด็กทั้งหมด
